## NWAGW, CHIBUIKEM CHRYSOGONUS

#### Question 1

### Concatenating two lists

In [3]:
A = [1,2,3,4,5,6]
B = [13,21,34]

A_B = A + B
print(A_B)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


### Question 2
### Creating identity matrix

In [6]:
import numpy as np
id = np.identity(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 3
### Lowest average cost of fuel per unit burned

#### Grouping by fuel type and fuel per unit burned, getting the sum
#### Getting the total number of fuel types  for the average
#### Sorting values to get the lowest average

In [7]:
import pandas as pd
import scipy.stats
fuel_data = pd.read_csv('C:\Users\DELL\Downloads\Hamoye Fuel Data.csv', error_bad_lines = False)
d1 = fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].sum()
d2 = fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].count()
d3 = (d1 / d2).sort_values()
print(d3)

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64


### Question 4
#### Standard deviation and 75th percentile

In [8]:
stdDeviation = fuel_data['fuel_mmbtu_per_unit'].std()
print(stdDeviation)

10.600220307806714


In [10]:
percentile = fuel_data['fuel_mmbtu_per_unit'].quantile(q = 0.75, interpolation = 'linear')
print(percentile)

17.006


### Question 5
#### Skewness and Kurtosis

In [11]:
skw = fuel_data['fuel_qty_burned'].skew()
kut = fuel_data['fuel_qty_burned'].kurt()

print("The skewness is: " + str(skw))
print("The kurtosis is: " + str(kut))

The skewness is: 15.851495469109503
The kurtosis is: 651.3694501337732


### Question 6
#### Missing value

#### to check if there are missing values and if so, get the sum

In [23]:
mod = fuel_data['fuel_unit'].isnull().sum()
print(mod)

180


##### Therefore we have 180 missing values in the data and all from fuel unit
#### To check the total number of rows

In [20]:
totalValue = fuel_data['fuel_unit'].count()
print(totalValue)

29343


#### Getting the percentage

In [35]:
percentage = ((mod / totalValue) * 100)
print("the percentage is: " + str(percentage))

the percentage is: 0


In [36]:
print("Feature: fuel unit, Total: %s, Percent: %s" %(mod, percentage))

Feature: fuel unit, Total: 180, Percent: 0


### Question 7
#### There are two types of variables: Categorical variables which are not numeric in nature and Numeric - which deals with numbers
#### The feature with missing value (fuel unit) is a categorical variable
#### We input based on the highest variable in the column. This is the mode
#### Hence, we have Categorical Variables and use Mode imputation

### Question 8
#### Correlation with Fuel Cost Per Unit Burned

In [25]:
r_1 = fuel_data[fuel_data.columns[:]].corr()['fuel_cost_per_unit_burned'][:]
r_2 = r_1.sort_values()
print(r_2)

utility_id_ferc1               -0.037863
fuel_qty_burned                -0.018535
fuel_mmbtu_per_unit            -0.010034
fuel_cost_per_mmbtu            -0.000437
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_cost_per_unit_burned       1.000000
Name: fuel_cost_per_unit_burned, dtype: float64


### Question 9
#### Percentage Change

In [33]:
yearly_cost = fuel_data.groupby(['report_year', 'fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].sum()
year_1994, year_1998 = yearly_cost.loc[[1994,1998], 'coal']
percent_change = ((year_1998 - year_1994) / year_1994) * 100
print(str(percent_change))

-20.5676545183


### Question 10

In [28]:
c1 = fuel_data.groupby('report_year')['fuel_cost_per_unit_delivered'].sum()
c2 = fuel_data.groupby('report_year')['fuel_cost_per_unit_delivered'].count()
c3 = (c1 / c2).sort_values()
print(c3)

report_year
1999       25.551627
1995       32.735269
2006       38.657484
2005       41.438184
2007       43.325023
2017       46.196861
2002       47.594361
2003       55.663493
2008       58.588197
2011       59.774667
2001       60.050396
2012       60.994502
1994       63.636060
2010       91.862105
2016      103.901761
2004      139.524275
2013      172.307591
2014      192.737183
1998      287.154420
2015      326.535511
2018      499.269966
2009      652.694163
2000      985.362877
1996     9196.705948
1997    11140.197239
Name: fuel_cost_per_unit_delivered, dtype: float64
